server:
  port: 8007
  servlet:
    context-path: /api
spring:
  application:
    name: api
  profiles:
    active: test
  aop:
    proxy-target-class: true
    auto: true
  freemarker:
    suffix: .ftl
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    settings:
      number_format: 0
      classic_compatible: true
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: Y
      logic-not-delete-value: N
  mapper-locations: classpath*:com/ejiaoyi/**/*Mapper.xml

